IBeer/Controllers/HomeController.cs
using IBeer.ViewModel;
using IBeerCore.Entities;
using IBeerService.Services;
using System.Collections.Generic;
using System.Web.Mvc;

namespace IBeer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<Drink> drinks = new DrinkService().GetAll();
            List<VMDrink> vms = new List<VMDrink>();
            foreach(var drink in drinks)
            {
                vms.Add(new VMDrink()
                            .SetName(drink.Name)
                            .SetBarCode(drink.BarCode)
                            .SetAmount(drink.Amount)
                            .SetLot(drink.LotID)
                            .SetLot(new LotService().GetByID(drink.LotID))
                            .SetStock(new StockService().GetByDrink(drink.BarCode))
                );
            }
            return View(vms);
        }
    }
}

IBeer/Controllers/ParameterController.cs
using IBeerCore.Entities;
using IBeerService.Services;
using System.Collections.Generic;
using System.Web.Mvc;

namespace IBeer.Controllers
{
    public class ParameterController : Controller
    {
        // GET: Parameter
        public ActionResult Parameters()
        {
            List<Parameter> parameters = new ParameterService().GetAll();
            return View(parameters);
        }
        
        public ActionResult Parameter(int id)
        {
            Parameter parameter = new ParameterService().GetById(id);
            return View(parameter);
        }

        [HttpPost]
        public ActionResult Edit(Parameter VMparameter)
        {
            ViewBag.Result = "Edição realizada com sucesso";
            if (ModelState.IsValid)
            {
                new ParameterService().Update(VMparameter);
                return View();
            }
            ViewBag.Result = "Erro ao editar parametro";
            return View();
        }
    }
}

IBeer/Controllers/PurchaseOrderController.cs
using IBeer.ViewModel;
using IBeerCore.Entities;
using IBeerService.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IBeer.Controllers
{
    public class PurchaseOrderController : Controller
    {
        // GET: PurchaseOrder
        public ActionResult Verify()
        {
            new PurchaseOrderService().GeneratePurcheseOrder();
            return View();
        }

        public ActionResult Purchases()
        {
            List<PurchaseOrder> purcharse = new PurchaseOrderService().GetAll();
            List<VMPurchase> vmPurchase = new List<VMPurchase>();
            foreach (var p in purcharse)
            {
                VMPurchase vm = new VMPurchase()
                {
                    Id = p.Id,
                    Total = p.Total,
                    Status = p.Status,
                    Provider = p.Provider
                };
                foreach(var item in p.Itens)
                {
                    var product = new DrinkService().GetByBarCode(item.BarCode);
                    vm.Itens = new List<VMPurchaseOrderItem>()
                    { new VMPurchaseOrderItem
                        {
                            Amount = item.Amount,
                            BarCode = item.BarCode,
                            Total = item.Total,
                            Value = item.Value,
                            Description = product.Name
                        }
                    };
                }
                vmPurchase.Add(vm);
            }
            return View(vmPurchase);
        }

        
        public ActionResult Update(int id, int status)
        {
            PurchaseOrder purchase = new PurchaseOrderService().GetById(id);
            purchase.SetStatus(status);
            new PurchaseOrderService().Update(purchase);
            return View();
        }
    }
}

IBeer/Controllers/StockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IBeer.Controllers
{
    public class StockController : Controller
    {
        // GET: Stock
        public ActionResult Index()
        {
            return View();
        }
    }
}

IBeer/Views/Home/Index.cshtml
@model List<IBeer.ViewModel.VMDrink>
@{
    ViewBag.Title = "Home Page";
}

<h2>Bebidas</h2>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Produto</th>
                    <th>Código de Barras</th>
                    <th>Quantidade</th>
                    <th>Lote</th>
                    <th>Validade</th>
                    <th>Est. Crítico</th>
                    <th>Est. Mínimo</th>
                    <th>Est. Máximo</th>
                    <th>Est. Total</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var drink in Model)
                {
                    <tr>
                        <td>@drink.Name</td>
                        <td>@drink.BarCode</td>
                        <td>@drink.Amount</td>
                        <td>@drink.Lot.Despription</td>
                        <td>@drink.Lot.ShelfLife</td>
                        <td>@drink.Stock.Critical</td>
                        <td>@drink.Stock.Minimun</td>
                        <td>@drink.Stock.Maximun</td>
                        <td>@drink.Stock.Amount</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@using(Html.BeginForm("Verify", "PurchaseOrder"))
{
    <input type="submit" class="btn" value="Gerar ordem de compra" />
}

IBeer/Views/Parameter/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@ViewBag.Result

IBeer/Views/Parameter/Parameter.cshtml
@model IBeerCore.Entities.Parameter
@{
ViewBag.Title = "Parameter";
}

<h2>Parâmetro</h2>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        @using (Html.BeginForm("Edit", "Parameter", FormMethod.Post))
        {
            if (Model.Description == "StockIdeal")
            {
                @Html.HiddenFor(x => x.Id)
                @Html.Label("Description:")
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                <br />
                @Html.Label("Valor:")
                @Html.DropDownListFor(x => x.Value, new List<SelectListItem>() { new SelectListItem { Text = "Mínimo", Value = "1" }, new SelectListItem { Text = "Médio", Value = "2" }, new SelectListItem { Text = "Máximo", Value = "3" } }, new { @class = "form-control" })

            }
            else
            {
                @Html.HiddenFor(x => x.Id)
                @Html.Label("Description:")
                @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
                <br />
                @Html.Label("Valor:")
                @Html.DropDownListFor(x => x.Value, new List<SelectListItem>() { new SelectListItem { Text = "Sim", Value = "True" }, new SelectListItem { Text = "Não", Value = "False" } }, new { @class = "form-control" })

            }

            <br />
            <input type="submit" value="Save">
        }
    </div>
</div>

IBeer/Views/Parameter/Parameters.cshtml
@model List<IBeerCore.Entities.Parameter>
@{
    ViewBag.Title = "Parameters";
}

<h2>Parameters</h2>
<br />
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Parametro</th>
                    <th>Valor</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var parameter in Model)
                {
                <tr>
                    <td>@parameter.Description</td>
                    @if (parameter.Value == "1")
                    {
                        <td>Mínimo</td>
                    }
                    @if (parameter.Value == "2")
                    {
                        <td>Médio</td>
                    }
                    @if (parameter.Value == "3")
                    {
                        <td>Máximo</td>
                    }
                    @if (parameter.Value == "False")
                    {
                        <td>Não</td>
                    }
                    @if (parameter.Value == "True")
                    {
                        <td>Sim</td>
                    }
                    <td>@Html.ActionLink("Edit", "Parameter", new { id = parameter.Id })</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

IBeer/Views/PurchaseOrder/Purchases.cshtml
@model List<IBeer.ViewModel.VMPurchase>
@{
    ViewBag.Title = "Purchases";
}

<h2>Ordens de Compra</h2>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Fornecedor</th>
                    <th>Status</th>
                    <th>Total</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var purchase in Model)
                {
                <tr>
                    <td>@purchase.Provider</td>
                    @if (purchase.Status == 1)
                    {
                        <td>Aguardando Aprovação</td>
                    }
                    @if (purchase.Status == 2)
                    {
                        <td>Reprovado</td>
                    }
                    @if (purchase.Status == 3)
                    {
                        <td>Aprovado</td>
                    }
                    @if (purchase.Status == 4)
                    {
                        <td>Aprovado automaticamente</td>
                    }
                    <td>@purchase.Total.ToString("N2")</td>
                    @if (purchase.Status == 1)
                    {
                        <td>@Html.ActionLink("Aprovar", "Update", new { id = purchase.Id, status = 3 })</td>
                        <td>@Html.ActionLink("Reprovar", "Update", new { id = purchase.Id, status = 2 })</td>
                    }

                </tr>
                <tr>
                    @foreach (var itens in purchase.Itens)
                    {
                        <td>Produto: @itens.BarCode - @itens.Description</td>
                        <td>Quantidade: @itens.Amount</td>
                        <td>Valor: R$ @itens.Value.ToString("N2")</td>
                        <td>Total: R$ @itens.Total.ToString("N2")</td>
                     }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

IBeer/Views/PurchaseOrder/Update.cshtml
@{
    ViewBag.Title = "Update";
}

<h2>Ordem de compra atualizada!</h2>

IBeer/Views/PurchaseOrder/Verify.cshtml
@{
    ViewBag.Title = "Verify";
}

<h2>Realizada geração de ordens de compra!</h2>
@Html.ActionLink("Visualizar ordens de compra", "Purchases")

IBeer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("IBeer", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bebidas", "Index", "Home")</li>
                    <li>@Html.ActionLink("Parametros", "Parameters", "Parameter")</li>
                    <li>@Html.ActionLink("Ordens de Compras", "Purchases", "PurchaseOrder")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - IBeer</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>